### ISSUE TITLE
Icon doesn't show in toolbar

### ISSUE THREAD

**Issue by rhespanhol** [Ghedeon/ADB-Uninstall#10]
I don't know if this is a bug from my side or from the new version.

I updated to the latest version but now the icon doesn't show in toolbar.

In Android studio event log i have this:
EmptyThrowable: Null child action in group Toolbar Run Actions () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=ADB Uninstall

**Comment by Ghedeon** [comment]
Could you try to uninstall and install it again? Right now I'm using AS 1.5 Preview (141.2314126) and both scenarios work for me: update and install from scratch.

If the issue persists, please, provide some additional info, such as OS and AS version.

**Comment by rhespanhol** [comment]
I did the both methods and the error keeps showing, i even tried to invalidate cache and restart AS:
EmptyThrowable: Null child action in group Toolbar Run Actions () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=ADB Uninstall

Im using AS 1.4 stable and osx 10.11.1

**Comment by Ghedeon** [comment]
Ok, I guess it's because of java version. Could you try this build, please?

https://github.com/Ghedeon/ADB-Uninstall/releases/download/1.1.3/ADB.Uninstall.jar

**Comment by rhespanhol** [comment]
It worked!! 
Thank you
