### ISSUE TITLE
Uninstalled wrong app

### ISSUE THREAD

**Issue by rhespanhol** [Ghedeon/ADB-Uninstall#9]
I have several build types and i wanted to uninstall the debug version but it uninstalled the release version.

here is my debug build type:

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-DEBUG'
            minifyEnabled false
            signingConfig signingConfigs.debug
        }

**Comment by Ghedeon** [comment]
Hi, to be honest I'm surprised that my plugin is still used, taking into account that AS is evolving and already contains required install/uninstall functionality)
```View → Tool Windows → Gradle → expand your project → Tasks → install```
Now, right click on desired uninstall<buildVariant> task, select Assign Shortcut. Voila, Profit!

Thanks for the feedback, I'm open for ideas, but probably it's time to mark this plugin as deprecated.

**Comment by zamesilyasa** [comment]
This is not actually the same.
Execution time is very different.
adb uninstall works immediately, but gradle task run all dependency tasks and result is:
Total time: 13.495 secs
Also this shortcut will replace current run configuration to the last gradle task.

But adb uninstall works perfectly jus in several milliseconds and will not touch configurations.

**Comment by Ghedeon** [comment]
I see your point, fair enough. Will update the plugin asap.

**Comment by Ghedeon** [comment]
Please, feel free to check the latest available version [1.1.2]. Should work with applicationId suffixes and flavors as well. Basically, it uninstalls currently selected buildVariant, no matter where it comes from and yes, it's instant). I also dismiss information bubble after 3 sec now, to make it less annoying.
